#!zsh

################################################################################
# Given input on STDIN, print only column number $1.

################################################################################
if [ "$#" -eq 1 ]; then
  cut -f $1
else
  read -A cols
  read -t -k 1 && cat > /dev/null

  echo 1 | \
    (
      PROMPT3=""
      select i in $cols; do
        break
      done
    )
fi
