#!zsh

################################################################################
# Given a file name, print which key encrypted that file.
key=`gpg2 --batch --decrypt --list-only --status-fd 1 $1 2> /dev/null | awk '/ENC_TO/ {print $3}'`
gpg2 --list-keys $key
