#!zsh

# Set default path
typeset -U path

# Load core environment variables.
source @prefix@zsh/lib/editor.zsh

# Other environment variables:
export VIRSH_DEFAULT_CONNECT_URI="qemu:///system"
export GPG_TTY=$(tty)
export OS=$(uname -s | tr '[A-Z]' '[a-z]')

# Load in optional operating system override
[ -r "@prefix@zsh/os/$OS" ] && source "@prefix@zsh/os/$OS"
