#!/usr/bin/env zsh

# Set default path
typeset -U path

# Add some standard directories to PATH.
[ -d ~/.cabal/bin ] && path=(~/.cabal/bin $path)

# Always keep ~/bin at the head of the list.
path=(~/bin $path)

# Load core environment variables.
source ~/.zsh/lib/agents.zsh
source ~/.zsh/lib/editor.zsh

# Load in optional operating system override
[ -r ~/.zsh/os ] && source ~/.zsh/os

# Load in optional local override file
[ -r ~/.zsh/local ] && source ~/.zsh/local
