#!/usr/bin/env zsh

# Set default path
typeset -U path

# Always keep ~/bin at the head of the list.
path=(~/bin $path)

# Load core environment variables.
source ~/.zsh/lib/editor.zsh

# Other environment variables:
export VIRSH_DEFAULT_CONNECT_URI="qemu:///system"
export GPG_TTY=`tty`

# Load in optional operating system override
[ -r ~/.zsh/os ] && source ~/.zsh/os

# Load in optional local override file
[ -r ~/.zsh/local ] && source ~/.zsh/local
