#!zsh

# keep some arrays unique
typeset -U fpath
typeset -U cdpath
typeset -U manpath

# some variables to export
export LESS="-SRiJMW"
export PAGER=less

# add our function path
functions_directory=@prefix@zsh/func
widgets_directory=@prefix@zsh/wids
fpath=($functions_directory $widgets_directory $fpath)

# clober stuff
setopt no_clobber
setopt hist_allow_clobber

# other options
setopt alwaystoend
setopt auto_cd
setopt auto_list
setopt completeinword
setopt correct
setopt magic_equal_subst
setopt mark_dirs
setopt multios
setopt no_auto_remove_slash
setopt no_beep
setopt no_correct_all
setopt rematch_pcre

# job control
setopt no_hup
setopt no_check_jobs

# autoload my functions
autoload -U ${fpath[1]}/*(:t)

# load some useful modules
zmodload zsh/datetime

# bring in other files
source @prefix@zsh/lib/bindings.zsh
source @prefix@zsh/lib/aliases.zsh
source @prefix@zsh/lib/hosts.zsh
source @prefix@zsh/lib/completion.zsh
source @prefix@zsh/lib/directories.zsh
source @prefix@zsh/lib/history.zsh
source @prefix@zsh/lib/syntax.zsh
source @prefix@zsh/lib/prompt.zsh

if which direnv > /dev/null 2>&1; then
  eval "$(direnv hook zsh)"
fi
