#!zsh

################################################################################
# NixOS internally knows where to search for man pages.  Help zsh auto
# complete on them.
if [ -n "$NIX_PATH" ]; then
  export MANPATH=`man -w`
fi

################################################################################
# Some aliases for Linux
alias vnc="ssvncviewer -escape Alt_L"

################################################################################
# Allow more control keys through in the terminal
if [ -t 1 ]; then
  stty stop undef
  stty start undef
fi
